# Generated by Django 4.2.2 on 2023-08-13 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_mesa_cli_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='facturado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
