# Generated by Django 4.2.2 on 2023-08-14 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_pedido_facturado_pedido_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='prod',
            new_name='producto',
        ),
    ]
